### ISSUE TITLE
Not Working when trying to host on Vercel

### ISSUE THREAD

**Issue by Irom1** [benborgers/opensheet#1]
On this domain: irom-opensheet.vercel.app I get this error when using your project on vercel:
[GET] /1OhIs5-6zJBG_IpKMNLx8Y8n0wpM6vFHit0GBpUMZor0/Absent%20Teachers
20:49:41:41
2021-10-26T00:49:42.793Z	undefined	ERROR	SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/var/task/api/index.js:4:21)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:170:25)
    at Loader.import (internal/modules/esm/loader.js:178:24)
    at getListener (/var/task/___vc/__launcher.js:33:11)
RequestId: a0202616-5bb7-409d-8bbb-65c57b907b3d Error: Runtime exited with error: exit status 1
Runtime.ExitError

**Comment by benborgers** [comment]
It looks like you’re hosting your own instance of opensheet on Vercel, which is great! 

Have you set the `GOOGLE_SERVICE_ACCOUNT` environment variable? If not, I can show you how to do that.

**Comment by Irom1** [comment]
Oh I didn’t do any configuration. Makes sense that I would have to. How do I do that?

**Comment by benborgers** [comment]
I just wrote up some instructions in the readme! Could you go through these instructions https://github.com/benborgers/opensheet#self-hosting and let me know if it’s successful?
